import * as off from "./OFFSETS.ts";

const bounds = {
    tick_counter: 7999992,
    sync_state: 7999996,
    ids: off.IDS_OFFSET,
    xs: off.XS_OFFSET,
    ys: off.YS_OFFSET,
    energy: off.ENERGY_OFFSET,
    resonance: off.RESONANCE_OFFSET,
    phase: off.PHASE_OFFSET,
    logic: off.LOGIC_OFFSET,
    bonds: off.BONDS_OFFSET,
    stiffness: off.STIFFNESS_OFFSET,
    instructions: off.INSTRUCTIONS_OFFSET,
    context: off.CONTEXT_OFFSET,
    evolution_reserved: off.EVOLUTION_OFFSET,
    spawn_requests: off.SPAWN_REQUESTS_OFFSET,
    meiosis: off.MEIOSIS_OFFSET,
    bond_requests: off.BOND_REQUESTS_OFFSET,
    spatial_grid: off.SPATIAL_GRID_OFFSET,
    roles: off.ROLES_OFFSET,
    structure_grid: off.STRUCTURE_GRID_OFFSET,
    signal_grid: off.SIGNAL_GRID_OFFSET,
    memory_grid: off.MEMORY_GRID_OFFSET,
    ascension_stats: off.ASCENSION_STATS_OFFSET,
    bond_distances: off.BOND_DISTANCES_OFFSET,
    damping: off.DAMPING_OFFSET,
    causality: off.CAUSALITY_OFFSET,
    hive_memory: off.HIVE_MEMORY_OFFSET,
    hive_balance: off.HIVE_BALANCE_OFFSET,
    quorum: off.QUORUM_OFFSET,
    coherence: off.COHERENCE_OFFSET,
    neural_coherence: off.NEURAL_COHERENCE_OFFSET,
    physics_read_xs: off.PHYSICS_READ_XS_OFFSET,
    physics_read_ys: off.PHYSICS_READ_YS_OFFSET,
    physics_read_energy: off.PHYSICS_READ_ENERGY_OFFSET,
    physics_read_resonance: off.PHYSICS_READ_RESONANCE_OFFSET,
    energy_delta: off.ENERGY_DELTA_OFFSET,
    resonance_delta: off.RESONANCE_DELTA_OFFSET,
    structure_build_owner: off.STRUCTURE_BUILD_OWNER_OFFSET,
    structure_build_value: off.STRUCTURE_BUILD_VALUE_OFFSET,
    structure_charge_intent: off.STRUCTURE_CHARGE_INTENT_OFFSET,
    attention_field: off.ATTENTION_FIELD_OFFSET,
    hive_energy_pool: off.HIVE_ENERGY_POOL_OFFSET,
    glyph_header: off.GLYPH_HEADER_OFFSET,
    glyph_payload: off.GLYPH_PAYLOAD_OFFSET,
    glyph_scratch_header: off.GLYPH_SCRATCH_HEADER_OFFSET,
    glyph_scratch_payload: off.GLYPH_SCRATCH_PAYLOAD_OFFSET,
    hormones: off.HORMONE_OFFSET,
    secretion_stats: off.SECRETION_STATS_OFFSET,
    lineage: off.LINEAGE_OFFSET,
    mailbox: off.MAILBOX_OFFSET,
    ledger_head: off.LEDGER_HEAD_OFFSET,
    ledger_data: off.LEDGER_DATA_OFFSET,
};


const sizes = {
   tick_counter: 4,
   sync_state: 4,
   ids: 8*500000,
   xs: 2*500000,
   ys: 2*500000,
   energy: 4*500000,
   resonance: 4*500000,
   phase: 4*500000,
   logic: 8*500000,
   bonds: 4*500000*4,
   stiffness: 4*500000*4,
   instructions: 64*500000,
   context: 64*500000,
   evolution_reserved: 4*500000,
   spawn_requests: 24584,
   meiosis: 4*300000,
   bond_requests: 4*500000*3,
   spatial_grid: 4*358400,
   roles: 1*500000,
   structure_grid: 4*11200,
   signal_grid: 4*11200,
   memory_grid: 8*11200,
   ascension_stats: 4*250000,
   bond_distances: 1*500000*4,
   damping: 1*500000,
   causality: 1*500000,
   hive_memory: 1024,
   hive_balance: 4,
   quorum: 4*100025,
   coherence: 4,
   neural_coherence: 4,
   physics_read_xs: 2*500000,
   physics_read_ys: 2*500000,
   physics_read_energy: 4*500000,
   physics_read_resonance: 4*500000,
   energy_delta: 4*500000,
   resonance_delta: 4*500000,
   structure_build_owner: 4*11200,
   structure_build_value: 4*11200,
   structure_charge_intent: 4*11200,
   attention_field: 4*11200,
   hive_energy_pool: 4*256,
   glyph_header: 4*11200,
   glyph_payload: 8*11200,
   glyph_scratch_header: 4*11200,
   glyph_scratch_payload: 8*11200,
   hormones: 2*8,
   secretion_stats: 4*12,
   lineage: 8*500000,
   mailbox: 8*500000,
   ledger_head: 4,
   ledger_data: 16*65536,
};

let current = 7999992;
for (const [k, v] of Object.entries(bounds)) {
    if (v > current) {
       let pad = v - current;
       console.log(`pub _pad_${k}: [u8; ${pad}], // to ${v}`);
    }
    
    // We don't type it out fully, just output the test blocks too
    console.log(`assert_eq!(offset_of!(SigmaMatrix, ${k}), ${v + 8}, "${k}");`);
    
    current = v + sizes[k];
}
