// AUTOGENERATED FACADE
// deno-lint-ignore-file camelcase
export * from "./00/mod.ts";
export * from "./01/mod.ts";
export * from "./02/mod.ts";
export * from "./03/mod.ts";
export * from "./04/mod.ts";
export * from "./05/mod.ts";
export * from "./06/mod.ts";
export * from "./07/mod.ts";
export * from "./08/mod.ts";
export * from "./09/mod.ts";
export * from "./10/mod.ts";
export * from "./11/mod.ts";
export * from "./12/mod.ts";
export * from "./13/mod.ts";
export * from "./14/mod.ts";
export * from "./15/mod.ts";
const envAsDir = Deno.env.get("GEN_DIR_AS") || "src/_as";
const envAsName = Deno.env.get("AS_WASM_NAME") || "release.wasm";
const wasmFile = envAsDir.endsWith("/") ? envAsDir + envAsName : envAsDir + "/" + envAsName;
export const AS_WASM_PATH = new URL(wasmFile, import.meta.url.replace("src/_/mod.ts", ""));
export const RUST_WASM_PATH = new URL("src/_rust/release.wasm", import.meta.url.replace("src/_/mod.ts", ""));
