// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Defines system-wide physical constants and enumerations for the OMEGA-64 Sigma Core.
//! These values are isomorphically synchronized with the TypeScript layer.

pub const MAX_ATOMS: usize = 500000;
pub const SAFETY_BUFFER: usize = 8000000;
pub const GRID_W: i32 = 140;
pub const GRID_H: i32 = 80;
pub const GRID_CELLS: usize = 11200;
pub const SPATIAL_CELL_SIZE: i32 = 10;
pub const WORLD_MAX_X: i32 = 1399;
pub const WORLD_MAX_Y: i32 = 799;
pub const SCALE: i32 = 1000;
pub const CELL_CAPACITY: usize = 32;
pub const MAX_PC: u8 = 64;
pub const MAX_EXECUTION_STEPS: usize = 64;
pub const ATOM_LOGIC_SIZE: usize = 64;
pub const MAX_LEDGER_EVENTS: usize = 65536;
pub const MAX_EGRESS_EVENTS: usize = 8192;
pub const WASM_PAGE_BYTES: usize = 65536;
pub const WASM_MEMORY_PAGES: usize = 7630;
pub const HIVE_MEMORY_SIZE: usize = 1024;
pub const HIVE_ENERGY_POOL_SIZE: usize = 256;
pub const MAX_HORMONES: usize = 8;
pub const SECRETION_STATS_SIZE: usize = 12;
pub const MAX_SPAWN_REQUESTS: usize = 1024;
pub const MAX_MEIOSIS_EVENTS: usize = 75000;
pub const MAX_ASCENSION_STATS: usize = 62500;
pub const MAX_ASCENSION_STATS_RESERVED: usize = 1250000;
pub const ATOM_CONTEXT_SIZE: usize = 16;
pub const ATOM_GENOME_SIZE: usize = 8;
pub const ATOM_INSTRUCTION_SIZE: usize = 64;
pub const RESOURCE_MAX: i32 = 2000000000;

pub const OP_NOP: u8 = 0;
pub const OP_SET: u8 = 1;
pub const OP_GET: u8 = 2;
pub const OP_PUT: u8 = 3;
pub const OP_ADD: u8 = 4;
pub const OP_SUB: u8 = 5;
pub const OP_JZ: u8 = 16;
pub const OP_JNZ: u8 = 17;
pub const OP_JMP: u8 = 18;
pub const OP_SYSCALL: u8 = 96;
pub const OP_REPLICATE: u8 = 128;
pub const OP_SIGNAL: u8 = 129;
pub const OP_BIND: u8 = 130;
pub const OP_SHARE: u8 = 131;
pub const OP_HEBB: u8 = 138;
pub const OP_FIRE: u8 = 139;
pub const OP_DECAY: u8 = 145;
pub const OP_PLUG: u8 = 164;
pub const OP_TENSEGRITY: u8 = 165;
pub const OP_COLLECTIVE: u8 = 166;
pub const OP_BUILD: u8 = 168;
pub const OP_SPORE_DRIVE: u8 = 168;
pub const OP_SENSE: u8 = 169;
pub const OP_SENSE_AS: u8 = 178;
pub const OP_SECRETE_PLASMID: u8 = 170;
pub const OP_INCORPORATE_PLASMID: u8 = 171;
pub const OP_RESOLVE: u8 = 176;
pub const OP_RESONATE_KURAMOTO: u8 = 177;
pub const PROP_ENERGY: u8 = 0;
pub const PROP_RESONANCE: u8 = 1;
pub const PROP_X: u8 = 2;
pub const PROP_Y: u8 = 3;
pub const PROP_PHASE: u8 = 4;
pub const PROP_GRID_CHARGE: u8 = 7;
pub const PROP_QUORUM: u8 = 8;
pub const PROP_NEURAL_COHERENCE: u8 = 9;
pub const PROP_MEMORY: u8 = 10;
pub const PROP_CONSENSUS: u8 = 11;
pub const SYS_YIELD: i32 = 1;
pub const SYS_READ_MEM: i32 = 2;
pub const SYS_WRITE_MEM: i32 = 3;
pub const SYS_SPAWN: i32 = 4;
pub const SYS_BIND: i32 = 5;
pub const SYS_SET_ROLE: i32 = 6;
pub const SYS_MUTATE: i32 = 7;
pub const SYS_MSG: i32 = 8;
pub const SYS_READ_INBOX: i32 = 9;
pub const SYS_TRANSFER: i32 = 10;
pub const SYS_REPLICATE: i32 = 11;
pub const SYS_EMIT: i32 = 12;
pub const SYS_SCAN: i32 = 13;
pub const SYS_MOVE: i32 = 14;
pub const SYS_EAT: i32 = 15;
pub const SYS_BET: i32 = 16;
pub const SYS_ATTRACT: i32 = 17;
pub const SYS_FOLD: i32 = 18;
pub const SYS_SPORE_DRIVE: i32 = 20;
pub const SYS_SENSE_PHASE: i32 = 21;

pub const U64_BYTES: usize = 8;
pub const I32_BYTES: usize = 4;
pub const I16_BYTES: usize = 2;
pub const F32_BYTES: usize = 4;
pub const SYNC_STATE_OFFSET: usize = SAFETY_BUFFER - 4;
pub const TICK_COUNTER_OFFSET: usize = SAFETY_BUFFER - 8;
pub const IDS_OFFSET: usize = SAFETY_BUFFER + 0;
pub const XS_OFFSET: usize = SAFETY_BUFFER + 4000000;
pub const YS_OFFSET: usize = SAFETY_BUFFER + 5000000;
pub const ENERGY_OFFSET: usize = SAFETY_BUFFER + 6000000;
pub const RESONANCE_OFFSET: usize = SAFETY_BUFFER + 8000000;
pub const PHASE_OFFSET: usize = SAFETY_BUFFER + 10000000;
pub const LOGIC_OFFSET: usize = SAFETY_BUFFER + 12000000;
pub const BONDS_OFFSET: usize = SAFETY_BUFFER + 16000000;
pub const STIFFNESS_OFFSET: usize = SAFETY_BUFFER + 24000000;
pub const INSTRUCTIONS_OFFSET: usize = SAFETY_BUFFER + 32000000;
pub const CONTEXT_OFFSET: usize = SAFETY_BUFFER + 64000000;
pub const EVOLUTION_OFFSET: usize = SAFETY_BUFFER + 96000000;
pub const INTENT_OFFSET: usize = EVOLUTION_OFFSET;
pub const SPAWN_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 98000000;
pub const MEIOSIS_OFFSET: usize = SAFETY_BUFFER + 98024584;
pub const BOND_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 104024584;
pub const SPATIAL_GRID_OFFSET: usize = SAFETY_BUFFER + 110024584;
pub const ROLES_OFFSET: usize = SAFETY_BUFFER + 111458184;
pub const STRUCTURE_GRID_OFFSET: usize = SAFETY_BUFFER + 111958184;
pub const SIGNAL_GRID_OFFSET: usize = SAFETY_BUFFER + 112002984;
pub const MEMORY_GRID_OFFSET: usize = SAFETY_BUFFER + 112047784;
pub const ASCENSION_STATS_OFFSET: usize = SAFETY_BUFFER + 112137384;
pub const BOND_DISTANCES_OFFSET: usize = SAFETY_BUFFER + 117137384;
pub const SYNAPTIC_WEIGHTS_OFFSET: usize = SAFETY_BUFFER + 119137384;
pub const DAMPING_OFFSET: usize = SAFETY_BUFFER + 121137384;
pub const CAUSALITY_OFFSET: usize = SAFETY_BUFFER + 121637384;
pub const HIVE_MEMORY_OFFSET: usize = SAFETY_BUFFER + 122137384;
pub const HIVE_BALANCE_OFFSET: usize = SAFETY_BUFFER + 122138408;
pub const QUORUM_OFFSET: usize = SAFETY_BUFFER + 122138412;
pub const COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496812;
pub const NEURAL_COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496816;
pub const PHYSICS_READ_XS_OFFSET: usize = SAFETY_BUFFER + 122496820;
pub const PHYSICS_READ_YS_OFFSET: usize = SAFETY_BUFFER + 123496820;
pub const PHYSICS_READ_ENERGY_OFFSET: usize = SAFETY_BUFFER + 124496820;
pub const PHYSICS_READ_RESONANCE_OFFSET: usize = SAFETY_BUFFER + 126496820;
pub const ENERGY_DELTA_OFFSET: usize = SAFETY_BUFFER + 128496820;
pub const RESONANCE_DELTA_OFFSET: usize = SAFETY_BUFFER + 130496820;
pub const STRUCTURE_BUILD_OWNER_OFFSET: usize = SAFETY_BUFFER + 132496820;
pub const STRUCTURE_BUILD_VALUE_OFFSET: usize = SAFETY_BUFFER + 132541620;
pub const STRUCTURE_CHARGE_INTENT_OFFSET: usize = SAFETY_BUFFER + 132586420;
pub const ATTENTION_FIELD_OFFSET: usize = SAFETY_BUFFER + 132631220;
pub const HIVE_ENERGY_POOL_OFFSET: usize = SAFETY_BUFFER + 132676020;
pub const GLYPH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132677044;
pub const GLYPH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132721844;
pub const GLYPH_SCRATCH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132811444;
pub const GLYPH_SCRATCH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132856244;
pub const HORMONE_OFFSET: usize = SAFETY_BUFFER + 132945844;
pub const SECRETION_STATS_OFFSET: usize = SAFETY_BUFFER + 132945860;
pub const LINEAGE_OFFSET: usize = SAFETY_BUFFER + 132945912;
pub const MAILBOX_OFFSET: usize = SAFETY_BUFFER + 136945912;
pub const LEDGER_HEAD_OFFSET: usize = SAFETY_BUFFER + 140945912;
pub const LEDGER_DATA_OFFSET: usize = SAFETY_BUFFER + 140945916;
pub const EGRESS_HEAD_OFFSET: usize = SAFETY_BUFFER + 141994492;
pub const EGRESS_DATA_OFFSET: usize = SAFETY_BUFFER + 141994496;
pub const LATTICE_MEMORY_END: usize = EGRESS_DATA_OFFSET + (MAX_EGRESS_EVENTS * 128);

/// Strongly typed roles for LambdaVM Atoms
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AtomRole {
    None = 0,
    Guardian = 1,
    Architect = 2,
    Artisan = 3,
    Parasite = 4,
    Mitochondria = 5,
    MetazoanFlag = 0x80,
}

impl AtomRole {
    pub fn from_u8(val: u8) -> Self {
        match val {
            1 => Self::Guardian,
            2 => Self::Architect,
            3 => Self::Artisan,
            4 => Self::Parasite,
            5 => Self::Mitochondria,
            0x80 => Self::MetazoanFlag,
            _ => Self::None,
        }
    }
}
