// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Defines system-wide physical constants and enumerations for the OMEGA-64 Sigma Core.
//! These values are isomorphically synchronized with the TypeScript layer.

pub const MAX_ATOMS: usize = 500000;
pub const SAFETY_BUFFER: usize = 8000000;
pub const GRID_W: i32 = 140;
pub const GRID_H: i32 = 80;
pub const GRID_CELLS: usize = 11200;
pub const SPATIAL_CELL_SIZE: i32 = 10;
pub const WORLD_MAX_X: i32 = 1399;
pub const WORLD_MAX_Y: i32 = 799;
pub const SCALE: i32 = 1000;
pub const CELL_CAPACITY: usize = 32;
pub const MAX_PC: u8 = 64;
pub const MAX_EXECUTION_STEPS: usize = 64;
pub const ATOM_LOGIC_SIZE: usize = 64;
pub const MAX_LEDGER_EVENTS: usize = 65536;
pub const MAX_EGRESS_EVENTS: usize = 8192;
pub const WASM_PAGE_BYTES: usize = 65536;
pub const WASM_MEMORY_PAGES: usize = 7630;
pub const HIVE_MEMORY_SIZE: usize = 1024;
pub const HIVE_ENERGY_POOL_SIZE: usize = 256;
pub const MAX_HORMONES: usize = 8;
pub const SECRETION_STATS_SIZE: usize = 12;
pub const ATOM_CONTEXT_SIZE: usize = 16;
pub const ATOM_GENOME_SIZE: usize = 8;
pub const ATOM_INSTRUCTION_SIZE: usize = 64;
pub const RESOURCE_MAX: i32 = 2000000000;

pub const OP_NOP: u8 = 0;
pub const OP_SET: u8 = 1;
pub const OP_GET: u8 = 2;
pub const OP_PUT: u8 = 3;
pub const OP_ADD: u8 = 4;
pub const OP_SUB: u8 = 5;
pub const OP_JZ: u8 = 16;
pub const OP_JNZ: u8 = 17;
pub const OP_JMP: u8 = 18;
pub const OP_SYSCALL: u8 = 96;
pub const OP_REPLICATE: u8 = 128;
pub const OP_SIGNAL: u8 = 129;
pub const OP_BIND: u8 = 130;
pub const OP_SHARE: u8 = 131;
pub const OP_HEBB: u8 = 138;
pub const OP_FIRE: u8 = 139;
pub const OP_DECAY: u8 = 145;
pub const OP_PLUG: u8 = 164;
pub const OP_TENSEGRITY: u8 = 165;
pub const OP_COLLECTIVE: u8 = 166;
pub const OP_BUILD: u8 = 168;
pub const OP_SPORE_DRIVE: u8 = 168;
pub const OP_SENSE: u8 = 169;
pub const OP_SENSE_AS: u8 = 178;
pub const OP_SECRETE_PLASMID: u8 = 170;
pub const OP_INCORPORATE_PLASMID: u8 = 171;
pub const OP_RESOLVE: u8 = 176;
pub const OP_RESONATE_KURAMOTO: u8 = 177;
pub const PROP_ENERGY: u8 = 0;
pub const PROP_RESONANCE: u8 = 1;
pub const PROP_X: u8 = 2;
pub const PROP_Y: u8 = 3;
pub const PROP_PHASE: u8 = 4;
pub const PROP_GRID_CHARGE: u8 = 7;
pub const PROP_QUORUM: u8 = 8;
pub const PROP_NEURAL_COHERENCE: u8 = 9;
pub const PROP_MEMORY: u8 = 10;
pub const PROP_CONSENSUS: u8 = 11;

/// Strongly typed roles for LambdaVM Atoms
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AtomRole {
    None = 0,
    Guardian = 1,
    Architect = 2,
    Artisan = 3,
    Parasite = 4,
    Mitochondria = 5,
    MetazoanFlag = 0x80,
}

impl AtomRole {
    pub fn from_u8(val: u8) -> Self {
        match val {
            1 => Self::Guardian,
            2 => Self::Architect,
            3 => Self::Artisan,
            4 => Self::Parasite,
            5 => Self::Mitochondria,
            0x80 => Self::MetazoanFlag,
            _ => Self::None,
        }
    }
}
