// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Defines system-wide physical constants and enumerations for the OMEGA-64 Sigma Core.
//! These values are isomorphically synchronized with the TypeScript layer.

pub const MAX_ATOMS: usize = 500000;
pub const SAFETY_BUFFER: usize = 8000000;
pub const GRID_W: i32 = 140;
pub const GRID_H: i32 = 80;
pub const GRID_CELLS: usize = 11200;
pub const SCALE: i32 = 1000;
pub const CELL_CAPACITY: usize = 32;
pub const MAX_PC: u8 = 64;
pub const MAX_EXECUTION_STEPS: usize = 64;
pub const ATOM_LOGIC_SIZE: usize = 64;
pub const MAX_LEDGER_EVENTS: usize = 65536;
pub const MAX_EGRESS_EVENTS: usize = 8192;
pub const WASM_PAGE_BYTES: usize = 65536;
pub const WASM_MEMORY_PAGES: usize = 7630;
pub const HIVE_MEMORY_SIZE: usize = 1024;
pub const HIVE_ENERGY_POOL_SIZE: usize = 256;
pub const MAX_HORMONES: usize = 8;
pub const SECRETION_STATS_SIZE: usize = 12;
pub const ATOM_CONTEXT_SIZE: usize = 16;
pub const ATOM_GENOME_SIZE: usize = 8;
pub const ATOM_INSTRUCTION_SIZE: usize = 64;

/// Strongly typed roles for LambdaVM Atoms
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AtomRole {
    None = 0,
    Guardian = 1,
    Architect = 2,
    Artisan = 3,
    Parasite = 4,
    Mitochondria = 5,
    MetazoanFlag = 0x80,
}

impl AtomRole {
    pub fn from_u8(val: u8) -> Self {
        match val {
            1 => Self::Guardian,
            2 => Self::Architect,
            3 => Self::Artisan,
            4 => Self::Parasite,
            5 => Self::Mitochondria,
            0x80 => Self::MetazoanFlag,
            _ => Self::None,
        }
    }
}
