// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Mathematical Coprocessor (Deterministic LUT Trigonometry)
// Math constants and logic migrated to Ontology Builder (src/ontology)
// To ensure a single source of truth, we re-export them from the ontology lib module.

// Include the aggregated ontology definitions directly into the math module namespace
include!("ontology_gen/mod.rs");

// Flatten the levels backwards into the math namespace so external code can just use `crate::math::math_sin`
pub use L01::*;
pub use L00::*;