// OMEGA-64 | Isomorphic Topological Generator | Era 69
// This script generates the symmetric physical constants for both Deno and Rust layers.

const SYSTEM_CONSTANTS: Record<string, [number, string]> = {
  MAX_ATOMS:           [500_000,   "usize"],
  SAFETY_BUFFER:       [8_000_000, "usize"],
  GRID_W:              [140,       "i32"],
  GRID_H:              [80,        "i32"],
  GRID_CELLS:          [140 * 80,  "usize"],
  SPATIAL_CELL_SIZE:   [10,        "i32"],
  WORLD_MAX_X:         [(140 * 10) - 1, "i32"],
  WORLD_MAX_Y:         [(80 * 10) - 1, "i32"],
  SCALE:               [1000,      "i32"],
  CELL_CAPACITY:       [32,        "usize"],
  MAX_PC:              [64,        "u8"],
  MAX_EXECUTION_STEPS: [64,        "usize"],
  ATOM_LOGIC_SIZE:     [64,        "usize"],
  MAX_LEDGER_EVENTS:   [65_536,    "usize"],
  MAX_EGRESS_EVENTS:   [8192,      "usize"],
  WASM_PAGE_BYTES:     [64 * 1024, "usize"],
  WASM_MEMORY_PAGES:   [7630,      "usize"],
  HIVE_MEMORY_SIZE:    [1024,      "usize"],
  HIVE_ENERGY_POOL_SIZE: [256,     "usize"],
  MAX_HORMONES:        [8,         "usize"],
  SECRETION_STATS_SIZE:[12,        "usize"],
  MAX_SPAWN_REQUESTS:  [1024,      "usize"],
  MAX_MEIOSIS_EVENTS:  [75000,     "usize"],
  MAX_ASCENSION_STATS: [62500,     "usize"],
  MAX_ASCENSION_STATS_RESERVED: [1250000, "usize"],
  ATOM_CONTEXT_SIZE:   [16,        "usize"],
  ATOM_GENOME_SIZE:    [8,         "usize"],
  ATOM_INSTRUCTION_SIZE: [64,      "usize"],
  RESOURCE_MAX:        [2_000_000_000, "i32"],
};

const VM_OPCODES: Record<string, number> = {
  OP_NOP: 0x00,
  OP_SET: 0x01,
  OP_GET: 0x02,
  OP_PUT: 0x03,
  OP_ADD: 0x04,
  OP_SUB: 0x05,
  OP_JZ: 0x10,
  OP_JNZ: 0x11,
  OP_JMP: 0x12,
  OP_SYSCALL: 0x60,
  OP_REPLICATE: 0x80,
  OP_SIGNAL: 0x81,
  OP_BIND: 0x82,
  OP_SHARE: 0x83,
  OP_HEBB: 0x8A,
  OP_FIRE: 0x8B,
  OP_DECAY: 0x91,
  OP_PLUG: 0xA4,
  OP_TENSEGRITY: 0xA5,
  OP_COLLECTIVE: 0xA6,
  OP_BUILD: 0xA8,
  OP_SPORE_DRIVE: 0xA8,
  OP_SENSE: 0xA9, // From Rust ISA
  OP_SENSE_AS: 0xB2, // From AS legacy
  OP_SECRETE_PLASMID: 0xAA,
  OP_INCORPORATE_PLASMID: 0xAB,
  OP_RESOLVE: 0xB0,
  OP_RESONATE_KURAMOTO: 0xB1,
};

const VM_PROPS: Record<string, number> = {
  PROP_ENERGY: 0,
  PROP_RESONANCE: 1,
  PROP_X: 2,
  PROP_Y: 3,
  PROP_PHASE: 4,
  PROP_GRID_CHARGE: 7,
  PROP_QUORUM: 8,
  PROP_NEURAL_COHERENCE: 9,
  PROP_MEMORY: 10,
  PROP_CONSENSUS: 11,
};

const VM_SYS: Record<string, number> = {
  SYS_YIELD: 1,
  SYS_READ_MEM: 2,
  SYS_WRITE_MEM: 3,
  SYS_SPAWN: 4,
  SYS_BIND: 5,
  SYS_SET_ROLE: 6,
  SYS_MUTATE: 7,
  SYS_MSG: 8,
  SYS_READ_INBOX: 9,
  SYS_TRANSFER: 10,
  SYS_REPLICATE: 11,
  SYS_EMIT: 12,
  SYS_SCAN: 13,
  SYS_MOVE: 14,
  SYS_EAT: 15,
  SYS_BET: 16,
  SYS_ATTRACT: 17,
  SYS_FOLD: 18,
  SYS_SPORE_DRIVE: 20,
  SYS_SENSE_PHASE: 21,
};

// Generate TypeScript Offsets (Imperative Shell)
const TS_OFFSETS = `// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
// OMEGA-64 | OFFSETS.ts | Era 69: Absolute Coherence
// Unified Memory Lattice Constants - Relocated for WASM Safety

${Object.entries(SYSTEM_CONSTANTS)
  .map(([name, [value, _]]) => `export const ${name} = ${value};`)
  .join("\n")}

${Object.entries(VM_OPCODES).map(([n,v]) => `export const ${n} = ${v};`).join('\n')}
${Object.entries(VM_PROPS).map(([n,v]) => `export const ${n} = ${v};`).join('\n')}
${Object.entries(VM_SYS).map(([n,v]) => `export const ${n} = ${v};`).join('\n')}

const U64_BYTES = 8;
const I32_BYTES = 4;
const I16_BYTES = 2;
const F32_BYTES = 4;

export const SYNC_STATE_OFFSET = SAFETY_BUFFER - 4;
export const TICK_COUNTER_OFFSET = SAFETY_BUFFER - 8;

export const IDS_OFFSET = SAFETY_BUFFER + 0;
export const XS_OFFSET = SAFETY_BUFFER + 4000000;
export const YS_OFFSET = SAFETY_BUFFER + 5000000;
export const ENERGY_OFFSET = SAFETY_BUFFER + 6000000;
export const RESONANCE_OFFSET = SAFETY_BUFFER + 8000000;
export const PHASE_OFFSET = SAFETY_BUFFER + 10000000;
export const LOGIC_OFFSET = SAFETY_BUFFER + 12000000;
export const BONDS_OFFSET = SAFETY_BUFFER + 16000000;
export const STIFFNESS_OFFSET = SAFETY_BUFFER + 24000000;
export const INSTRUCTIONS_OFFSET = SAFETY_BUFFER + 32000000;
export const CONTEXT_OFFSET = SAFETY_BUFFER + 64000000;
export const EVOLUTION_OFFSET = SAFETY_BUFFER + 96000000;
export const INTENT_OFFSET = EVOLUTION_OFFSET;
export const SPAWN_REQUESTS_OFFSET = SAFETY_BUFFER + 98000000;
export const MEIOSIS_OFFSET = SAFETY_BUFFER + 98024584;
export const BOND_REQUESTS_OFFSET = SAFETY_BUFFER + 104024584;
export const SPATIAL_GRID_OFFSET = SAFETY_BUFFER + 110024584;
export const ROLES_OFFSET = SAFETY_BUFFER + 111458184;
export const STRUCTURE_GRID_OFFSET = SAFETY_BUFFER + 111958184;
export const SIGNAL_GRID_OFFSET = SAFETY_BUFFER + 112002984;
export const MEMORY_GRID_OFFSET = SAFETY_BUFFER + 112047784;
export const ASCENSION_STATS_OFFSET = SAFETY_BUFFER + 112137384;
export const BOND_DISTANCES_OFFSET = SAFETY_BUFFER + 117137384;
export const SYNAPTIC_WEIGHTS_OFFSET = SAFETY_BUFFER + 119137384;
export const DAMPING_OFFSET = SAFETY_BUFFER + 121137384;
export const CAUSALITY_OFFSET = SAFETY_BUFFER + 121637384;
export const HIVE_MEMORY_OFFSET = SAFETY_BUFFER + 122137384;
export const HIVE_BALANCE_OFFSET = SAFETY_BUFFER + 122138408;
export const QUORUM_OFFSET = SAFETY_BUFFER + 122138412;
export const COHERENCE_OFFSET = SAFETY_BUFFER + 122496812;
export const NEURAL_COHERENCE_OFFSET = SAFETY_BUFFER + 122496816;
export const PHYSICS_READ_XS_OFFSET = SAFETY_BUFFER + 122496820;
export const PHYSICS_READ_YS_OFFSET = SAFETY_BUFFER + 123496820;
export const PHYSICS_READ_ENERGY_OFFSET = SAFETY_BUFFER + 124496820;
export const PHYSICS_READ_RESONANCE_OFFSET = SAFETY_BUFFER + 126496820;
export const ENERGY_DELTA_OFFSET = SAFETY_BUFFER + 128496820;
export const RESONANCE_DELTA_OFFSET = SAFETY_BUFFER + 130496820;
export const STRUCTURE_BUILD_OWNER_OFFSET = SAFETY_BUFFER + 132496820;
export const STRUCTURE_BUILD_VALUE_OFFSET = SAFETY_BUFFER + 132541620;
export const STRUCTURE_CHARGE_INTENT_OFFSET = SAFETY_BUFFER + 132586420;
export const ATTENTION_FIELD_OFFSET = SAFETY_BUFFER + 132631220;
export const HIVE_ENERGY_POOL_OFFSET = SAFETY_BUFFER + 132676020;
export const GLYPH_HEADER_OFFSET = SAFETY_BUFFER + 132677044;
export const GLYPH_PAYLOAD_OFFSET = SAFETY_BUFFER + 132721844;
export const GLYPH_SCRATCH_HEADER_OFFSET = SAFETY_BUFFER + 132811444;
export const GLYPH_SCRATCH_PAYLOAD_OFFSET = SAFETY_BUFFER + 132856244;
export const HORMONE_OFFSET = SAFETY_BUFFER + 132945844;
export const SECRETION_STATS_OFFSET = SAFETY_BUFFER + 132945860;
export const LINEAGE_OFFSET = SAFETY_BUFFER + 132945912;
export const MAILBOX_OFFSET = SAFETY_BUFFER + 136945912;

export const LEDGER_HEAD_OFFSET = SAFETY_BUFFER + 140945912;
export const LEDGER_DATA_OFFSET = SAFETY_BUFFER + 140945916;

export const EGRESS_HEAD_OFFSET = SAFETY_BUFFER + 141994492;
export const EGRESS_DATA_OFFSET = SAFETY_BUFFER + 141994496;

type MemoryLayoutRegion = { name: string; offset: number; size: number; align: number; };

export type MemoryLayoutValidationResult = { ok: boolean; errors: string[]; regions: MemoryLayoutRegion[]; latticeEnd: number; wasmBytes: number; };

const region = (name: string, offset: number, size: number, align: number): MemoryLayoutRegion => ({ name, offset, size, align });

export const MEMORY_LAYOUT_REGIONS: MemoryLayoutRegion[] = [
  region("TICK_COUNTER", TICK_COUNTER_OFFSET, I32_BYTES, I32_BYTES),
  region("SYNC_STATE", SYNC_STATE_OFFSET, I32_BYTES, I32_BYTES),
  region("IDS", IDS_OFFSET, MAX_ATOMS * U64_BYTES, U64_BYTES),
  region("XS", XS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("YS", YS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("ENERGY", ENERGY_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("RESONANCE", RESONANCE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("PHASE", PHASE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("LOGIC", LOGIC_OFFSET, MAX_ATOMS * ATOM_GENOME_SIZE, 1),
  region("BONDS", BONDS_OFFSET, MAX_ATOMS * 4 * I32_BYTES, I32_BYTES),
  region("STIFFNESS", STIFFNESS_OFFSET, MAX_ATOMS * 4 * F32_BYTES, F32_BYTES),
  region("INSTRUCTIONS", INSTRUCTIONS_OFFSET, MAX_ATOMS * ATOM_INSTRUCTION_SIZE, 1),
  region("CONTEXT", CONTEXT_OFFSET, MAX_ATOMS * ATOM_INSTRUCTION_SIZE, I32_BYTES),
  region("EVOLUTION", EVOLUTION_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("SPAWN_REQUESTS", SPAWN_REQUESTS_OFFSET, 8 + (1024 * 24), 8),
  region("MEIOSIS_RESERVED", MEIOSIS_OFFSET, BOND_REQUESTS_OFFSET - MEIOSIS_OFFSET, I32_BYTES),
  region("BOND_REQUESTS", BOND_REQUESTS_OFFSET, MAX_ATOMS * 3 * I32_BYTES, I32_BYTES),
  region("SPATIAL_GRID", SPATIAL_GRID_OFFSET, GRID_CELLS * 32 * I32_BYTES, I32_BYTES),
  region("ROLES", ROLES_OFFSET, MAX_ATOMS, 1),
  region("STRUCTURE_GRID", STRUCTURE_GRID_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("SIGNAL_GRID", SIGNAL_GRID_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("MEMORY_GRID", MEMORY_GRID_OFFSET, GRID_CELLS * 8, 1),
  region("ASCENSION_STATS_RESERVED", ASCENSION_STATS_OFFSET, BOND_DISTANCES_OFFSET - ASCENSION_STATS_OFFSET, I32_BYTES),
  region("BOND_DISTANCES", BOND_DISTANCES_OFFSET, MAX_ATOMS * 4, 1),
  region("SYNAPTIC_WEIGHTS", SYNAPTIC_WEIGHTS_OFFSET, MAX_ATOMS * 4, 1),
  region("DAMPING", DAMPING_OFFSET, MAX_ATOMS, 1),
  region("CAUSALITY", CAUSALITY_OFFSET, MAX_ATOMS, 1),
  region("HIVE_MEMORY", HIVE_MEMORY_OFFSET, HIVE_MEMORY_SIZE, 1),
  region("HIVE_BALANCE", HIVE_BALANCE_OFFSET, I32_BYTES, I32_BYTES),
  region("QUORUM", QUORUM_OFFSET, COHERENCE_OFFSET - QUORUM_OFFSET, I32_BYTES),
  region("COHERENCE", COHERENCE_OFFSET, I32_BYTES, I32_BYTES),
  region("NEURAL_COHERENCE", NEURAL_COHERENCE_OFFSET, I32_BYTES, I32_BYTES),
  region("PHYSICS_READ_XS", PHYSICS_READ_XS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("PHYSICS_READ_YS", PHYSICS_READ_YS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("PHYSICS_READ_ENERGY", PHYSICS_READ_ENERGY_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("PHYSICS_READ_RESONANCE", PHYSICS_READ_RESONANCE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("ENERGY_DELTA", ENERGY_DELTA_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("RESONANCE_DELTA", RESONANCE_DELTA_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_BUILD_OWNER", STRUCTURE_BUILD_OWNER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_BUILD_VALUE", STRUCTURE_BUILD_VALUE_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_CHARGE_INTENT", STRUCTURE_CHARGE_INTENT_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("ATTENTION_FIELD", ATTENTION_FIELD_OFFSET, GRID_CELLS * F32_BYTES, F32_BYTES),
  region("HIVE_ENERGY_POOL", HIVE_ENERGY_POOL_OFFSET, HIVE_ENERGY_POOL_SIZE * I32_BYTES, I32_BYTES),
  region("GLYPH_HEADER", GLYPH_HEADER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("GLYPH_PAYLOAD", GLYPH_PAYLOAD_OFFSET, GRID_CELLS * 8, 1),
  region("GLYPH_SCRATCH_HEADER", GLYPH_SCRATCH_HEADER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("GLYPH_SCRATCH_PAYLOAD", GLYPH_SCRATCH_PAYLOAD_OFFSET, GRID_CELLS * 8, 1),
  region("HORMONES", HORMONE_OFFSET, MAX_HORMONES * 2, 2),
  region("SECRETION_STATS", SECRETION_STATS_OFFSET, SECRETION_STATS_SIZE * 4, 4),
  region("LINEAGE", LINEAGE_OFFSET, MAX_ATOMS * U64_BYTES, U64_BYTES),
  region("MAILBOX", MAILBOX_OFFSET, MAX_ATOMS * 8, I32_BYTES),
  region("LEDGER_HEAD", LEDGER_HEAD_OFFSET, 4, 4),
  region("LEDGER_DATA", LEDGER_DATA_OFFSET, MAX_LEDGER_EVENTS * 16, 4),
  region("EGRESS_HEAD", EGRESS_HEAD_OFFSET, 4, 4),
  region("EGRESS_DATA", EGRESS_DATA_OFFSET, MAX_EGRESS_EVENTS * 128, 4),
];

export const LATTICE_MEMORY_END = EGRESS_DATA_OFFSET + (MAX_EGRESS_EVENTS * 128);
export const MIN_WASM_MEMORY_PAGES = Math.max(2600, Math.ceil(LATTICE_MEMORY_END / WASM_PAGE_BYTES));
export const WASM_MEMORY_BYTES = WASM_MEMORY_PAGES * WASM_PAGE_BYTES;

export const validateMemoryLayout = (wasmBytes: number = WASM_MEMORY_BYTES): MemoryLayoutValidationResult => {
  const errors: string[] = [];
  const sorted = [...MEMORY_LAYOUT_REGIONS].sort((a, b) => a.offset - b.offset);

  for (const item of sorted) {
    if (!Number.isFinite(item.offset) || !Number.isFinite(item.size)) {
      errors.push(\`[\${item.name}] offset/size must be finite numbers\`);
      continue;
    }
    if (item.size <= 0) errors.push(\`[\${item.name}] size must be > 0, got \${item.size}\`);
    if (item.align <= 0) {
      errors.push(\`[\${item.name}] align must be > 0, got \${item.align}\`);
    } else if (item.offset % item.align !== 0) {
      errors.push(\`[\${item.name}] misaligned offset=\${item.offset} align=\${item.align}\`);
    }
    const end = item.offset + item.size;
    if (end > wasmBytes) errors.push(\`[\${item.name}] out of wasm bounds: end=\${end} > wasmBytes=\${wasmBytes}\`);
  }

  for (let i = 1; i < sorted.length; i++) {
    const prev = sorted[i - 1]; const next = sorted[i];
    const prevEnd = prev.offset + prev.size;
    if (prevEnd > next.offset) errors.push(\`[\${prev.name}] overlaps [\${next.name}] (\${prevEnd} > \${next.offset})\`);
  }

  const maxRegionEnd = sorted.reduce((max, item) => Math.max(max, item.offset + item.size), 0);
  if (maxRegionEnd > LATTICE_MEMORY_END) errors.push(\`[LATTICE_MEMORY_END] too small: \${LATTICE_MEMORY_END} < required=\${maxRegionEnd}\`);

  return { ok: errors.length === 0, errors, regions: sorted, latticeEnd: LATTICE_MEMORY_END, wasmBytes };
};

export const MAX_ASCENSIONS_PER_TICK = 64;
`;


const rsLayoutVariables = "pub const U64_BYTES: usize = 8;\npub const I32_BYTES: usize = 4;\npub const I16_BYTES: usize = 2;\npub const F32_BYTES: usize = 4;\npub const SYNC_STATE_OFFSET: usize = SAFETY_BUFFER - 4;\npub const TICK_COUNTER_OFFSET: usize = SAFETY_BUFFER - 8;\npub const IDS_OFFSET: usize = SAFETY_BUFFER + 0;\npub const XS_OFFSET: usize = SAFETY_BUFFER + 4000000;\npub const YS_OFFSET: usize = SAFETY_BUFFER + 5000000;\npub const ENERGY_OFFSET: usize = SAFETY_BUFFER + 6000000;\npub const RESONANCE_OFFSET: usize = SAFETY_BUFFER + 8000000;\npub const PHASE_OFFSET: usize = SAFETY_BUFFER + 10000000;\npub const LOGIC_OFFSET: usize = SAFETY_BUFFER + 12000000;\npub const BONDS_OFFSET: usize = SAFETY_BUFFER + 16000000;\npub const STIFFNESS_OFFSET: usize = SAFETY_BUFFER + 24000000;\npub const INSTRUCTIONS_OFFSET: usize = SAFETY_BUFFER + 32000000;\npub const CONTEXT_OFFSET: usize = SAFETY_BUFFER + 64000000;\npub const EVOLUTION_OFFSET: usize = SAFETY_BUFFER + 96000000;\npub const INTENT_OFFSET: usize = EVOLUTION_OFFSET;\npub const SPAWN_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 98000000;\npub const MEIOSIS_OFFSET: usize = SAFETY_BUFFER + 98024584;\npub const BOND_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 104024584;\npub const SPATIAL_GRID_OFFSET: usize = SAFETY_BUFFER + 110024584;\npub const ROLES_OFFSET: usize = SAFETY_BUFFER + 111458184;\npub const STRUCTURE_GRID_OFFSET: usize = SAFETY_BUFFER + 111958184;\npub const SIGNAL_GRID_OFFSET: usize = SAFETY_BUFFER + 112002984;\npub const MEMORY_GRID_OFFSET: usize = SAFETY_BUFFER + 112047784;\npub const ASCENSION_STATS_OFFSET: usize = SAFETY_BUFFER + 112137384;\npub const BOND_DISTANCES_OFFSET: usize = SAFETY_BUFFER + 117137384;\npub const SYNAPTIC_WEIGHTS_OFFSET: usize = SAFETY_BUFFER + 119137384;\npub const DAMPING_OFFSET: usize = SAFETY_BUFFER + 121137384;\npub const CAUSALITY_OFFSET: usize = SAFETY_BUFFER + 121637384;\npub const HIVE_MEMORY_OFFSET: usize = SAFETY_BUFFER + 122137384;\npub const HIVE_BALANCE_OFFSET: usize = SAFETY_BUFFER + 122138408;\npub const QUORUM_OFFSET: usize = SAFETY_BUFFER + 122138412;\npub const COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496812;\npub const NEURAL_COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496816;\npub const PHYSICS_READ_XS_OFFSET: usize = SAFETY_BUFFER + 122496820;\npub const PHYSICS_READ_YS_OFFSET: usize = SAFETY_BUFFER + 123496820;\npub const PHYSICS_READ_ENERGY_OFFSET: usize = SAFETY_BUFFER + 124496820;\npub const PHYSICS_READ_RESONANCE_OFFSET: usize = SAFETY_BUFFER + 126496820;\npub const ENERGY_DELTA_OFFSET: usize = SAFETY_BUFFER + 128496820;\npub const RESONANCE_DELTA_OFFSET: usize = SAFETY_BUFFER + 130496820;\npub const STRUCTURE_BUILD_OWNER_OFFSET: usize = SAFETY_BUFFER + 132496820;\npub const STRUCTURE_BUILD_VALUE_OFFSET: usize = SAFETY_BUFFER + 132541620;\npub const STRUCTURE_CHARGE_INTENT_OFFSET: usize = SAFETY_BUFFER + 132586420;\npub const ATTENTION_FIELD_OFFSET: usize = SAFETY_BUFFER + 132631220;\npub const HIVE_ENERGY_POOL_OFFSET: usize = SAFETY_BUFFER + 132676020;\npub const GLYPH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132677044;\npub const GLYPH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132721844;\npub const GLYPH_SCRATCH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132811444;\npub const GLYPH_SCRATCH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132856244;\npub const HORMONE_OFFSET: usize = SAFETY_BUFFER + 132945844;\npub const SECRETION_STATS_OFFSET: usize = SAFETY_BUFFER + 132945860;\npub const LINEAGE_OFFSET: usize = SAFETY_BUFFER + 132945912;\npub const MAILBOX_OFFSET: usize = SAFETY_BUFFER + 136945912;\npub const LEDGER_HEAD_OFFSET: usize = SAFETY_BUFFER + 140945912;\npub const LEDGER_DATA_OFFSET: usize = SAFETY_BUFFER + 140945916;\npub const EGRESS_HEAD_OFFSET: usize = SAFETY_BUFFER + 141994492;\npub const EGRESS_DATA_OFFSET: usize = SAFETY_BUFFER + 141994496;\npub const LATTICE_MEMORY_END: usize = EGRESS_DATA_OFFSET + (MAX_EGRESS_EVENTS * 128);";

// Generate Rust Constants (Functional Core)
const RS_CONSTANTS = `// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Defines system-wide physical constants and enumerations for the OMEGA-64 Sigma Core.
//! These values are isomorphically synchronized with the TypeScript layer.

${Object.entries(SYSTEM_CONSTANTS)
  .map(([name, [value, type]]) => `pub const ${name}: ${type} = ${value};`)
  .join("\n")}

${Object.entries(VM_OPCODES).map(([n,v]) => `pub const ${n}: u8 = ${v};`).join('\n')}
${Object.entries(VM_PROPS).map(([n,v]) => `pub const ${n}: u8 = ${v};`).join('\n')}
${Object.entries(VM_SYS).map(([n,v]) => `pub const ${n}: i32 = ${v};`).join('\n')}

${rsLayoutVariables}

/// Strongly typed roles for LambdaVM Atoms
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AtomRole {
    None = 0,
    Guardian = 1,
    Architect = 2,
    Artisan = 3,
    Parasite = 4,
    Mitochondria = 5,
    MetazoanFlag = 0x80,
}

impl AtomRole {
    pub fn from_u8(val: u8) -> Self {
        match val {
            1 => Self::Guardian,
            2 => Self::Architect,
            3 => Self::Artisan,
            4 => Self::Parasite,
            5 => Self::Mitochondria,
            0x80 => Self::MetazoanFlag,
            _ => Self::None,
        }
    }
}
`;

Deno.writeTextFileSync(new URL("./OFFSETS.ts", import.meta.url), TS_OFFSETS);
Deno.writeTextFileSync(new URL("./sigma_core/src/constants.rs", import.meta.url), RS_CONSTANTS);

// Generate Mathematical LUTs (Q15 deterministic trig)
const SIN_LUT = Array.from({length: 256}, (_, i) => Math.round(Math.sin((i / 256) * Math.PI * 2) * 32767));
const COS_LUT = Array.from({length: 256}, (_, i) => Math.round(Math.cos((i / 256) * Math.PI * 2) * 32767));

const MATH_LUT_RS = `// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
//! Mathematical Coprocessor (Deterministic LUT Trigonometry)

pub const SIN_LUT: [i16; 256] = [
${SIN_LUT.map((v, i) => (i % 16 === 0 ? "    " : "") + v.toString().padStart(6) + ",").join(" ").replace(/ {4}/g, "\n    ")}
];

pub const COS_LUT: [i16; 256] = [
${COS_LUT.map((v, i) => (i % 16 === 0 ? "    " : "") + v.toString().padStart(6) + ",").join(" ").replace(/ {4}/g, "\n    ")}
];

pub const C_LOG2_C_LUT: [i32; 65] = [
0, 0, 2000, 4755, 8000, 11610, 15510, 19651, 24000, 28529, 33219, 38054, 43020, 48106, 53303, 58603, 64000, 69487, 75059, 80711, 86439, 92239, 98107, 104042, 110039, 116096, 122211, 128382, 134606, 140881, 147207, 153580, 160000, 166465, 172974, 179525, 186117, 192750, 199421, 206131, 212877, 219660, 226477, 233329, 240215, 247133, 254084, 261066, 268078, 275121, 282193, 289294, 296423, 303580, 310764, 317975, 325212, 332475, 339763, 347076, 354413, 361775, 369160, 376569, 384000
];

pub fn math_sin(angle: i32, high_res: i32) -> i32 {
    if high_res == 0 {
        let idx = (angle & 255) as usize;
        return SIN_LUT[idx] as i32;
    }
    let idx = ((angle >> 8) & 255) as usize;
    let frac = angle & 255;
    
    if high_res == 1 {
        let v0 = SIN_LUT[idx] as i32;
        let v1 = SIN_LUT[(idx + 1) & 255] as i32;
        return v0 + (((v1 - v0) * frac) >> 8);
    }
    
    // TAYLOR2
    let s_base = SIN_LUT[idx] as i32;
    let c_base = COS_LUT[idx] as i32;
    let d1 = (c_base * 804) >> 15;
    let term1 = (d1 * frac) >> 8;
    let d2 = (s_base * 10) >> 15;
    let term2 = (d2 * frac * frac) >> 16;
    s_base + term1 - term2
}

pub fn math_cos(angle: i32, high_res: i32) -> i32 {
    if high_res == 0 {
        let idx = (angle & 255) as usize;
        return COS_LUT[idx] as i32;
    }
    let idx = ((angle >> 8) & 255) as usize;
    let frac = angle & 255;
    
    if high_res == 1 {
        let v0 = COS_LUT[idx] as i32;
        let v1 = COS_LUT[(idx + 1) & 255] as i32;
        return v0 + (((v1 - v0) * frac) >> 8);
    }
    
    let s_base = SIN_LUT[idx] as i32;
    let c_base = COS_LUT[idx] as i32;
    let d1 = (s_base * 804) >> 15;
    let term1 = (d1 * frac) >> 8;
    let d2 = (c_base * 10) >> 15;
    let term2 = (d2 * frac * frac) >> 16;
    c_base - term1 - term2
}

pub fn calculate_shannon_entropy(data: &[u8; 64]) -> i32 {
    let mut counts = [0i32; 256];
    for &b in data.iter() {
        counts[b as usize] += 1;
    }

    let mut sum_c_log_c = 0;
    for &c in counts.iter() {
        if c > 0 {
            sum_c_log_c += C_LOG2_C_LUT[c as usize];
        }
    }

    let mut entropy = 6000 - (sum_c_log_c >> 6);
    
    if entropy < 0 {
        entropy = 0;
    } else if entropy > 6000 {
        entropy = 6000;
    }
    
    entropy
}
`;

Deno.writeTextFileSync(new URL("./sigma_core/src/math.rs", import.meta.url), MATH_LUT_RS);

const AS_CONSTANTS = `// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
// OMEGA-64 | constants.assembly.ts | Era 69
// Isomorphic WASM Constants and Math LUTs

${Object.entries(SYSTEM_CONSTANTS)
  .map(([name, [value, type]]) => {
    const asType = (name === "MAX_ATOMS") ? "i32" : type;
    return `export const ${name}: ${asType} = ${value};`;
  })
  .join("\n")}

${Object.entries(VM_OPCODES).map(([n,v]) => `export const ${n}: u8 = ${v};`).join('\n')}
${Object.entries(VM_PROPS).map(([n,v]) => `export const ${n}: u8 = ${v};`).join('\n')}
${Object.entries(VM_SYS).map(([n,v]) => `export const ${n}: i32 = ${v};`).join('\n')}

export const SYNC_STATE_OFFSET: usize = SAFETY_BUFFER - 4;
export const TICK_COUNTER_OFFSET: usize = SAFETY_BUFFER - 8;
export const TICK_COUNTER_OFF: usize = TICK_COUNTER_OFFSET;
export const IDS_OFFSET: usize = SAFETY_BUFFER + 0;
export const XS_OFFSET: usize = SAFETY_BUFFER + 4000000;
export const YS_OFFSET: usize = SAFETY_BUFFER + 5000000;
export const ENERGY_OFFSET: usize = SAFETY_BUFFER + 6000000;
export const RESONANCE_OFFSET: usize = SAFETY_BUFFER + 8000000;
export const PHASE_OFFSET: usize = SAFETY_BUFFER + 10000000;
export const LOGIC_OFFSET: usize = SAFETY_BUFFER + 12000000;
export const BONDS_OFFSET: usize = SAFETY_BUFFER + 16000000;
export const STIFFNESS_OFFSET: usize = SAFETY_BUFFER + 24000000;
export const INSTRUCTIONS_OFFSET: usize = SAFETY_BUFFER + 32000000;
export const GENOMES_OFFSET: usize = INSTRUCTIONS_OFFSET;
export const CONTEXT_OFFSET: usize = SAFETY_BUFFER + 64000000;
export const EVOLUTION_OFFSET: usize = SAFETY_BUFFER + 96000000;
export const INTENT_OFFSET: usize = EVOLUTION_OFFSET;
export const SPAWN_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 98000000;
export const SPAWN_REQUESTS_OFF: usize = SPAWN_REQUESTS_OFFSET;
export const SPAWN_GRID_OFF: usize = SPAWN_REQUESTS_OFFSET;
export const SPAWN_HEAD_OFF: usize = SPAWN_GRID_OFF;
export const SPAWN_DATA_OFF: usize = SPAWN_GRID_OFF + 8;
export const MEIOSIS_OFFSET: usize = SAFETY_BUFFER + 98024584;
export const METABOLISM_SCRATCH_OFF: usize = MEIOSIS_OFFSET;
export const BOND_REQUESTS_OFFSET: usize = SAFETY_BUFFER + 104024584;
export const SPATIAL_GRID_OFFSET: usize = SAFETY_BUFFER + 110024584;
export const ROLES_OFFSET: usize = SAFETY_BUFFER + 111458184;
export const STRUCTURE_GRID_OFFSET: usize = SAFETY_BUFFER + 111958184;
export const STRUCTURE_GRID_OFF: usize = STRUCTURE_GRID_OFFSET;
export const SIGNAL_GRID_OFFSET: usize = SAFETY_BUFFER + 112002984;
export const SIGNAL_GRID_OFF: usize = SIGNAL_GRID_OFFSET;
export const MEMORY_GRID_OFFSET: usize = SAFETY_BUFFER + 112047784;
export const MEMORY_GRID_OFF: usize = MEMORY_GRID_OFFSET;
export const ASCENSION_STATS_OFFSET: usize = SAFETY_BUFFER + 112137384;
export const ASCENSION_STATS_OFF: usize = ASCENSION_STATS_OFFSET;
export const BOND_DISTANCES_OFFSET: usize = SAFETY_BUFFER + 117137384;
export const BOND_DIST_OFF: usize = BOND_DISTANCES_OFFSET;
export const SYNAPTIC_WEIGHTS_OFFSET: usize = SAFETY_BUFFER + 119137384;
export const DAMPING_OFFSET: usize = SAFETY_BUFFER + 121137384;
export const DAMPING_OFF: usize = DAMPING_OFFSET;
export const CAUSALITY_OFFSET: usize = SAFETY_BUFFER + 121637384;
export const CAUSALITY_OFF: usize = CAUSALITY_OFFSET;
export const HIVE_MEMORY_OFFSET: usize = SAFETY_BUFFER + 122137384;
export const HIVE_MEMORY_OFF: usize = HIVE_MEMORY_OFFSET;
export const HIVE_BALANCE_OFFSET: usize = SAFETY_BUFFER + 122138408;
export const HIVE_BALANCE_OFF: usize = HIVE_BALANCE_OFFSET;
export const QUORUM_OFFSET: usize = SAFETY_BUFFER + 122138412;
export const COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496812;
export const COHERENCE_OFF: usize = COHERENCE_OFFSET;
export const NEURAL_COHERENCE_OFFSET: usize = SAFETY_BUFFER + 122496816;
export const NEURAL_COHERENCE_OFF: usize = NEURAL_COHERENCE_OFFSET;
export const PHYSICS_READ_XS_OFFSET: usize = SAFETY_BUFFER + 122496820;
export const PHYSICS_READ_XS_OFF: usize = PHYSICS_READ_XS_OFFSET;
export const PHYSICS_READ_YS_OFFSET: usize = SAFETY_BUFFER + 123496820;
export const PHYSICS_READ_YS_OFF: usize = PHYSICS_READ_YS_OFFSET;
export const PHYSICS_READ_ENERGY_OFFSET: usize = SAFETY_BUFFER + 124496820;
export const PHYSICS_READ_ENERGY_OFF: usize = PHYSICS_READ_ENERGY_OFFSET;
export const PHYSICS_READ_RESONANCE_OFFSET: usize = SAFETY_BUFFER + 126496820;
export const PHYSICS_READ_RESONANCE_OFF: usize = PHYSICS_READ_RESONANCE_OFFSET;
export const ENERGY_DELTA_OFFSET: usize = SAFETY_BUFFER + 128496820;
export const ENERGY_DELTA_OFF: usize = ENERGY_DELTA_OFFSET;
export const RESONANCE_DELTA_OFFSET: usize = SAFETY_BUFFER + 130496820;
export const RESONANCE_DELTA_OFF: usize = RESONANCE_DELTA_OFFSET;
export const STRUCTURE_BUILD_OWNER_OFFSET: usize = SAFETY_BUFFER + 132496820;
export const STRUCTURE_BUILD_OWNER_OFF: usize = STRUCTURE_BUILD_OWNER_OFFSET;
export const STRUCTURE_BUILD_VALUE_OFFSET: usize = SAFETY_BUFFER + 132541620;
export const STRUCTURE_BUILD_VALUE_OFF: usize = STRUCTURE_BUILD_VALUE_OFFSET;
export const STRUCTURE_CHARGE_INTENT_OFFSET: usize = SAFETY_BUFFER + 132586420;
export const STRUCTURE_CHARGE_INTENT_OFF: usize = STRUCTURE_CHARGE_INTENT_OFFSET;
export const ATTENTION_FIELD_OFFSET: usize = SAFETY_BUFFER + 132631220;
export const ATTENTION_FIELD_OFF: usize = ATTENTION_FIELD_OFFSET;
export const HIVE_ENERGY_POOL_OFFSET: usize = SAFETY_BUFFER + 132676020;
export const HIVE_ENERGY_POOL_OFF: usize = HIVE_ENERGY_POOL_OFFSET;
export const GLYPH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132677044;
export const GLYPH_HEADER_OFF: usize = GLYPH_HEADER_OFFSET;
export const GLYPH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132721844;
export const GLYPH_PAYLOAD_OFF: usize = GLYPH_PAYLOAD_OFFSET;
export const GLYPH_SCRATCH_HEADER_OFFSET: usize = SAFETY_BUFFER + 132811444;
export const GLYPH_SCRATCH_HEADER_OFF: usize = GLYPH_SCRATCH_HEADER_OFFSET;
export const GLYPH_SCRATCH_PAYLOAD_OFFSET: usize = SAFETY_BUFFER + 132856244;
export const GLYPH_SCRATCH_PAYLOAD_OFF: usize = GLYPH_SCRATCH_PAYLOAD_OFFSET;
export const HORMONE_OFFSET: usize = SAFETY_BUFFER + 132945844;
export const HORMONE_OFF: usize = HORMONE_OFFSET;
export const SECRETION_STATS_OFFSET: usize = SAFETY_BUFFER + 132945860;
export const SECRETION_STATS_OFF: usize = SECRETION_STATS_OFFSET;
export const LINEAGE_OFFSET: usize = SAFETY_BUFFER + 132945912;
export const MAILBOX_OFFSET: usize = SAFETY_BUFFER + 136945912;
export const LEDGER_HEAD_OFFSET: usize = SAFETY_BUFFER + 140945912;
export const LEDGER_DATA_OFFSET: usize = SAFETY_BUFFER + 140945916;
export const EGRESS_HEAD_OFFSET: usize = SAFETY_BUFFER + 141994492;
export const EGRESS_DATA_OFFSET: usize = SAFETY_BUFFER + 141994496;

export const SPAWN_MAX: i32 = 1024;
export const SPAWN_SLOT: i32 = 24;
export const LATTICE_MEMORY_END: usize = EGRESS_DATA_OFFSET + (MAX_EGRESS_EVENTS * 128);

// Mathematical Trigonometric LUTs (Q15 Format)
export const SIN_LUT: StaticArray<i16> = [
${SIN_LUT.map((v, i) => (i % 16 === 0 ? "    " : "") + v.toString().padStart(6) + ",").join(" ").replace(/ {4}/g, "\n    ")}
];

export const COS_LUT: StaticArray<i16> = [
${COS_LUT.map((v, i) => (i % 16 === 0 ? "    " : "") + v.toString().padStart(6) + ",").join(" ").replace(/ {4}/g, "\n    ")}
];
`;

Deno.writeTextFileSync(new URL("./01/assembly/constants.assembly.ts", import.meta.url), AS_CONSTANTS);
console.log("[DAG] Successfully generated Isomorphic Topology (`OFFSETS.ts`, `constants.rs`, `math.rs`, and `constants.assembly.ts`)");
