// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
// OMEGA-64 | OFFSETS.ts | Era 69: Absolute Coherence
// Unified Memory Lattice Constants - Relocated for WASM Safety

export const MAX_ATOMS = 500000;
export const SAFETY_BUFFER = 8000000;
export const GRID_W = 140;
export const GRID_H = 80;
export const GRID_CELLS = 11200;
export const SPATIAL_CELL_SIZE = 10;
export const WORLD_MAX_X = 1399;
export const WORLD_MAX_Y = 799;
export const SCALE = 1000;
export const CELL_CAPACITY = 32;
export const MAX_PC = 64;
export const MAX_EXECUTION_STEPS = 64;
export const ATOM_LOGIC_SIZE = 64;
export const MAX_LEDGER_EVENTS = 65536;
export const MAX_EGRESS_EVENTS = 8192;
export const WASM_PAGE_BYTES = 65536;
export const WASM_MEMORY_PAGES = 7630;
export const HIVE_MEMORY_SIZE = 1024;
export const HIVE_ENERGY_POOL_SIZE = 256;
export const MAX_HORMONES = 8;
export const SECRETION_STATS_SIZE = 12;
export const ATOM_CONTEXT_SIZE = 16;
export const ATOM_GENOME_SIZE = 8;
export const ATOM_INSTRUCTION_SIZE = 64;
export const RESOURCE_MAX = 2000000000;

export const OP_NOP = 0;
export const OP_SET = 1;
export const OP_GET = 2;
export const OP_PUT = 3;
export const OP_ADD = 4;
export const OP_SUB = 5;
export const OP_JZ = 16;
export const OP_JNZ = 17;
export const OP_JMP = 18;
export const OP_SYSCALL = 96;
export const OP_REPLICATE = 128;
export const OP_SIGNAL = 129;
export const OP_BIND = 130;
export const OP_SHARE = 131;
export const OP_HEBB = 138;
export const OP_FIRE = 139;
export const OP_DECAY = 145;
export const OP_PLUG = 164;
export const OP_TENSEGRITY = 165;
export const OP_COLLECTIVE = 166;
export const OP_BUILD = 168;
export const OP_SPORE_DRIVE = 168;
export const OP_SENSE = 169;
export const OP_SENSE_AS = 178;
export const OP_SECRETE_PLASMID = 170;
export const OP_INCORPORATE_PLASMID = 171;
export const OP_RESOLVE = 176;
export const OP_RESONATE_KURAMOTO = 177;
export const PROP_ENERGY = 0;
export const PROP_RESONANCE = 1;
export const PROP_X = 2;
export const PROP_Y = 3;
export const PROP_PHASE = 4;
export const PROP_GRID_CHARGE = 7;
export const PROP_QUORUM = 8;
export const PROP_NEURAL_COHERENCE = 9;
export const PROP_MEMORY = 10;
export const PROP_CONSENSUS = 11;

const U64_BYTES = 8;
const I32_BYTES = 4;
const I16_BYTES = 2;
const F32_BYTES = 4;

export const SYNC_STATE_OFFSET = SAFETY_BUFFER - 4;
export const TICK_COUNTER_OFFSET = SAFETY_BUFFER - 8;

export const IDS_OFFSET = SAFETY_BUFFER + 0;
export const XS_OFFSET = SAFETY_BUFFER + 4000000;
export const YS_OFFSET = SAFETY_BUFFER + 5000000;
export const ENERGY_OFFSET = SAFETY_BUFFER + 6000000;
export const RESONANCE_OFFSET = SAFETY_BUFFER + 8000000;
export const PHASE_OFFSET = SAFETY_BUFFER + 10000000;
export const LOGIC_OFFSET = SAFETY_BUFFER + 12000000;
export const BONDS_OFFSET = SAFETY_BUFFER + 16000000;
export const STIFFNESS_OFFSET = SAFETY_BUFFER + 24000000;
export const INSTRUCTIONS_OFFSET = SAFETY_BUFFER + 32000000;
export const CONTEXT_OFFSET = SAFETY_BUFFER + 64000000;
export const EVOLUTION_OFFSET = SAFETY_BUFFER + 96000000;
export const INTENT_OFFSET = EVOLUTION_OFFSET;
export const SPAWN_REQUESTS_OFFSET = SAFETY_BUFFER + 98000000;
export const MEIOSIS_OFFSET = SAFETY_BUFFER + 98024584;
export const BOND_REQUESTS_OFFSET = SAFETY_BUFFER + 104024584;
export const SPATIAL_GRID_OFFSET = SAFETY_BUFFER + 110024584;
export const ROLES_OFFSET = SAFETY_BUFFER + 111458184;
export const STRUCTURE_GRID_OFFSET = SAFETY_BUFFER + 111958184;
export const SIGNAL_GRID_OFFSET = SAFETY_BUFFER + 112002984;
export const MEMORY_GRID_OFFSET = SAFETY_BUFFER + 112047784;
export const ASCENSION_STATS_OFFSET = SAFETY_BUFFER + 112137384;
export const BOND_DISTANCES_OFFSET = SAFETY_BUFFER + 117137384;
export const SYNAPTIC_WEIGHTS_OFFSET = SAFETY_BUFFER + 119137384;
export const DAMPING_OFFSET = SAFETY_BUFFER + 121137384;
export const CAUSALITY_OFFSET = SAFETY_BUFFER + 121637384;
export const HIVE_MEMORY_OFFSET = SAFETY_BUFFER + 122137384;
export const HIVE_BALANCE_OFFSET = SAFETY_BUFFER + 122138408;
export const QUORUM_OFFSET = SAFETY_BUFFER + 122138412;
export const COHERENCE_OFFSET = SAFETY_BUFFER + 122496812;
export const NEURAL_COHERENCE_OFFSET = SAFETY_BUFFER + 122496816;
export const PHYSICS_READ_XS_OFFSET = SAFETY_BUFFER + 122496820;
export const PHYSICS_READ_YS_OFFSET = SAFETY_BUFFER + 123496820;
export const PHYSICS_READ_ENERGY_OFFSET = SAFETY_BUFFER + 124496820;
export const PHYSICS_READ_RESONANCE_OFFSET = SAFETY_BUFFER + 126496820;
export const ENERGY_DELTA_OFFSET = SAFETY_BUFFER + 128496820;
export const RESONANCE_DELTA_OFFSET = SAFETY_BUFFER + 130496820;
export const STRUCTURE_BUILD_OWNER_OFFSET = SAFETY_BUFFER + 132496820;
export const STRUCTURE_BUILD_VALUE_OFFSET = SAFETY_BUFFER + 132541620;
export const STRUCTURE_CHARGE_INTENT_OFFSET = SAFETY_BUFFER + 132586420;
export const ATTENTION_FIELD_OFFSET = SAFETY_BUFFER + 132631220;
export const HIVE_ENERGY_POOL_OFFSET = SAFETY_BUFFER + 132676020;
export const GLYPH_HEADER_OFFSET = SAFETY_BUFFER + 132677044;
export const GLYPH_PAYLOAD_OFFSET = SAFETY_BUFFER + 132721844;
export const GLYPH_SCRATCH_HEADER_OFFSET = SAFETY_BUFFER + 132811444;
export const GLYPH_SCRATCH_PAYLOAD_OFFSET = SAFETY_BUFFER + 132856244;
export const HORMONE_OFFSET = SAFETY_BUFFER + 132945844;
export const SECRETION_STATS_OFFSET = SAFETY_BUFFER + 132945860;
export const LINEAGE_OFFSET = SAFETY_BUFFER + 132945912;
export const MAILBOX_OFFSET = SAFETY_BUFFER + 136945912;

export const LEDGER_HEAD_OFFSET = SAFETY_BUFFER + 140945912;
export const LEDGER_DATA_OFFSET = SAFETY_BUFFER + 140945916;

export const EGRESS_HEAD_OFFSET = SAFETY_BUFFER + 141994492;
export const EGRESS_DATA_OFFSET = SAFETY_BUFFER + 141994496;

type MemoryLayoutRegion = { name: string; offset: number; size: number; align: number; };

export type MemoryLayoutValidationResult = { ok: boolean; errors: string[]; regions: MemoryLayoutRegion[]; latticeEnd: number; wasmBytes: number; };

const region = (name: string, offset: number, size: number, align: number): MemoryLayoutRegion => ({ name, offset, size, align });

export const MEMORY_LAYOUT_REGIONS: MemoryLayoutRegion[] = [
  region("TICK_COUNTER", TICK_COUNTER_OFFSET, I32_BYTES, I32_BYTES),
  region("SYNC_STATE", SYNC_STATE_OFFSET, I32_BYTES, I32_BYTES),
  region("IDS", IDS_OFFSET, MAX_ATOMS * U64_BYTES, U64_BYTES),
  region("XS", XS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("YS", YS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("ENERGY", ENERGY_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("RESONANCE", RESONANCE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("PHASE", PHASE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("LOGIC", LOGIC_OFFSET, MAX_ATOMS * ATOM_GENOME_SIZE, 1),
  region("BONDS", BONDS_OFFSET, MAX_ATOMS * 4 * I32_BYTES, I32_BYTES),
  region("STIFFNESS", STIFFNESS_OFFSET, MAX_ATOMS * 4 * F32_BYTES, F32_BYTES),
  region("INSTRUCTIONS", INSTRUCTIONS_OFFSET, MAX_ATOMS * ATOM_INSTRUCTION_SIZE, 1),
  region("CONTEXT", CONTEXT_OFFSET, MAX_ATOMS * ATOM_INSTRUCTION_SIZE, I32_BYTES),
  region("EVOLUTION", EVOLUTION_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("SPAWN_REQUESTS", SPAWN_REQUESTS_OFFSET, 8 + (1024 * 24), 8),
  region("MEIOSIS_RESERVED", MEIOSIS_OFFSET, BOND_REQUESTS_OFFSET - MEIOSIS_OFFSET, I32_BYTES),
  region("BOND_REQUESTS", BOND_REQUESTS_OFFSET, MAX_ATOMS * 3 * I32_BYTES, I32_BYTES),
  region("SPATIAL_GRID", SPATIAL_GRID_OFFSET, GRID_CELLS * 32 * I32_BYTES, I32_BYTES),
  region("ROLES", ROLES_OFFSET, MAX_ATOMS, 1),
  region("STRUCTURE_GRID", STRUCTURE_GRID_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("SIGNAL_GRID", SIGNAL_GRID_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("MEMORY_GRID", MEMORY_GRID_OFFSET, GRID_CELLS * 8, 1),
  region("ASCENSION_STATS_RESERVED", ASCENSION_STATS_OFFSET, BOND_DISTANCES_OFFSET - ASCENSION_STATS_OFFSET, I32_BYTES),
  region("BOND_DISTANCES", BOND_DISTANCES_OFFSET, MAX_ATOMS * 4, 1),
  region("SYNAPTIC_WEIGHTS", SYNAPTIC_WEIGHTS_OFFSET, MAX_ATOMS * 4, 1),
  region("DAMPING", DAMPING_OFFSET, MAX_ATOMS, 1),
  region("CAUSALITY", CAUSALITY_OFFSET, MAX_ATOMS, 1),
  region("HIVE_MEMORY", HIVE_MEMORY_OFFSET, HIVE_MEMORY_SIZE, 1),
  region("HIVE_BALANCE", HIVE_BALANCE_OFFSET, I32_BYTES, I32_BYTES),
  region("QUORUM", QUORUM_OFFSET, COHERENCE_OFFSET - QUORUM_OFFSET, I32_BYTES),
  region("COHERENCE", COHERENCE_OFFSET, I32_BYTES, I32_BYTES),
  region("NEURAL_COHERENCE", NEURAL_COHERENCE_OFFSET, I32_BYTES, I32_BYTES),
  region("PHYSICS_READ_XS", PHYSICS_READ_XS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("PHYSICS_READ_YS", PHYSICS_READ_YS_OFFSET, MAX_ATOMS * I16_BYTES, I16_BYTES),
  region("PHYSICS_READ_ENERGY", PHYSICS_READ_ENERGY_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("PHYSICS_READ_RESONANCE", PHYSICS_READ_RESONANCE_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("ENERGY_DELTA", ENERGY_DELTA_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("RESONANCE_DELTA", RESONANCE_DELTA_OFFSET, MAX_ATOMS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_BUILD_OWNER", STRUCTURE_BUILD_OWNER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_BUILD_VALUE", STRUCTURE_BUILD_VALUE_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("STRUCTURE_CHARGE_INTENT", STRUCTURE_CHARGE_INTENT_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("ATTENTION_FIELD", ATTENTION_FIELD_OFFSET, GRID_CELLS * F32_BYTES, F32_BYTES),
  region("HIVE_ENERGY_POOL", HIVE_ENERGY_POOL_OFFSET, HIVE_ENERGY_POOL_SIZE * I32_BYTES, I32_BYTES),
  region("GLYPH_HEADER", GLYPH_HEADER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("GLYPH_PAYLOAD", GLYPH_PAYLOAD_OFFSET, GRID_CELLS * 8, 1),
  region("GLYPH_SCRATCH_HEADER", GLYPH_SCRATCH_HEADER_OFFSET, GRID_CELLS * I32_BYTES, I32_BYTES),
  region("GLYPH_SCRATCH_PAYLOAD", GLYPH_SCRATCH_PAYLOAD_OFFSET, GRID_CELLS * 8, 1),
  region("HORMONES", HORMONE_OFFSET, MAX_HORMONES * 2, 2),
  region("SECRETION_STATS", SECRETION_STATS_OFFSET, SECRETION_STATS_SIZE * 4, 4),
  region("LINEAGE", LINEAGE_OFFSET, MAX_ATOMS * U64_BYTES, U64_BYTES),
  region("MAILBOX", MAILBOX_OFFSET, MAX_ATOMS * 8, I32_BYTES),
  region("LEDGER_HEAD", LEDGER_HEAD_OFFSET, 4, 4),
  region("LEDGER_DATA", LEDGER_DATA_OFFSET, MAX_LEDGER_EVENTS * 16, 4),
  region("EGRESS_HEAD", EGRESS_HEAD_OFFSET, 4, 4),
  region("EGRESS_DATA", EGRESS_DATA_OFFSET, MAX_EGRESS_EVENTS * 128, 4),
];

export const LATTICE_MEMORY_END = EGRESS_DATA_OFFSET + (MAX_EGRESS_EVENTS * 128);
export const MIN_WASM_MEMORY_PAGES = Math.max(2600, Math.ceil(LATTICE_MEMORY_END / WASM_PAGE_BYTES));
export const WASM_MEMORY_BYTES = WASM_MEMORY_PAGES * WASM_PAGE_BYTES;

export const validateMemoryLayout = (wasmBytes: number = WASM_MEMORY_BYTES): MemoryLayoutValidationResult => {
  const errors: string[] = [];
  const sorted = [...MEMORY_LAYOUT_REGIONS].sort((a, b) => a.offset - b.offset);

  for (const item of sorted) {
    if (!Number.isFinite(item.offset) || !Number.isFinite(item.size)) {
      errors.push(`[${item.name}] offset/size must be finite numbers`);
      continue;
    }
    if (item.size <= 0) errors.push(`[${item.name}] size must be > 0, got ${item.size}`);
    if (item.align <= 0) {
      errors.push(`[${item.name}] align must be > 0, got ${item.align}`);
    } else if (item.offset % item.align !== 0) {
      errors.push(`[${item.name}] misaligned offset=${item.offset} align=${item.align}`);
    }
    const end = item.offset + item.size;
    if (end > wasmBytes) errors.push(`[${item.name}] out of wasm bounds: end=${end} > wasmBytes=${wasmBytes}`);
  }

  for (let i = 1; i < sorted.length; i++) {
    const prev = sorted[i - 1]; const next = sorted[i];
    const prevEnd = prev.offset + prev.size;
    if (prevEnd > next.offset) errors.push(`[${prev.name}] overlaps [${next.name}] (${prevEnd} > ${next.offset})`);
  }

  const maxRegionEnd = sorted.reduce((max, item) => Math.max(max, item.offset + item.size), 0);
  if (maxRegionEnd > LATTICE_MEMORY_END) errors.push(`[LATTICE_MEMORY_END] too small: ${LATTICE_MEMORY_END} < required=${maxRegionEnd}`);

  return { ok: errors.length === 0, errors, regions: sorted, latticeEnd: LATTICE_MEMORY_END, wasmBytes };
};

export const MAX_ASCENSIONS_PER_TICK = 64;
