// AUTOGENERATED - DO NOT EDIT DIRECTLY (See generate.ts)
// OMEGA-64 | OFFSETS.ts | Era 69: Absolute Coherence
// Unified Memory Lattice Constants - Relocated for WASM Safety
export const MAX_ATOMS = 500000;
export const SAFETY_BUFFER = 8000000;
export const GRID_W = 140;
export const GRID_H = 80;
export const GRID_CELLS = 11200;
export const SPATIAL_CELL_SIZE = 10;
export const WORLD_MAX_X = 1399;
export const WORLD_MAX_Y = 799;
export const SCALE = 1000;
export const CELL_CAPACITY = 32;
export const MAX_PC = 64;
export const MAX_EXECUTION_STEPS = 64;
export const ATOM_LOGIC_SIZE = 64;
export const MAX_LEDGER_EVENTS = 65536;
export const MAX_EGRESS_EVENTS = 8192;
export const WASM_PAGE_BYTES = 65536;
export const WASM_MEMORY_PAGES = 7630;
export const HIVE_MEMORY_SIZE = 1024;
export const HIVE_ENERGY_POOL_SIZE = 256;
export const MAX_HORMONES = 8;
export const SECRETION_STATS_SIZE = 12;
export const MAX_SPAWN_REQUESTS = 1024;
export const MAX_MEIOSIS_EVENTS = 75000;
export const MAX_ASCENSION_STATS = 62500;
export const MAX_ASCENSION_STATS_RESERVED = 1250000;
export const ATOM_CONTEXT_SIZE = 16;
export const ATOM_GENOME_SIZE = 8;
export const ATOM_INSTRUCTION_SIZE = 64;
export const RESOURCE_MAX = 2000000000;
export const MAX_GLYPH_AMP = 8388607;
export const MIN_GLYPH_AMP = -8388608;
export const SPAWN_MAX = 1024;
export const SPAWN_SLOT = 24;
export const OP_NOP = 0;
export const OP_SET = 1;
export const OP_GET = 2;
export const OP_PUT = 3;
export const OP_ADD = 4;
export const OP_SUB = 5;
export const OP_JZ = 16;
export const OP_JNZ = 17;
export const OP_JMP = 18;
export const OP_SYSCALL = 96;
export const OP_REPLICATE = 128;
export const OP_SIGNAL = 129;
export const OP_BIND = 130;
export const OP_SHARE = 131;
export const OP_HEBB = 138;
export const OP_FIRE = 139;
export const OP_DECAY = 145;
export const OP_PLUG = 164;
export const OP_TENSEGRITY = 165;
export const OP_COLLECTIVE = 166;
export const OP_BUILD = 168;
export const OP_SPORE_DRIVE = 168;
export const OP_SENSE = 169;
export const OP_SENSE_AS = 178;
export const OP_SECRETE_PLASMID = 170;
export const OP_INCORPORATE_PLASMID = 171;
export const OP_RESOLVE = 176;
export const OP_RESONATE_KURAMOTO = 177;
export const PROP_ENERGY = 0;
export const PROP_RESONANCE = 1;
export const PROP_X = 2;
export const PROP_Y = 3;
export const PROP_PHASE = 4;
export const PROP_GRID_CHARGE = 7;
export const PROP_QUORUM = 8;
export const PROP_NEURAL_COHERENCE = 9;
export const PROP_MEMORY = 10;
export const PROP_CONSENSUS = 11;
export const SYS_YIELD = 1;
export const SYS_READ_MEM = 2;
export const SYS_WRITE_MEM = 3;
export const SYS_SPAWN = 4;
export const SYS_BIND = 5;
export const SYS_SET_ROLE = 6;
export const SYS_MUTATE = 7;
export const SYS_MSG = 8;
export const SYS_READ_INBOX = 9;
export const SYS_TRANSFER = 10;
export const SYS_REPLICATE = 11;
export const SYS_EMIT = 12;
export const SYS_SCAN = 13;
export const SYS_MOVE = 14;
export const SYS_EAT = 15;
export const SYS_BET = 16;
export const SYS_ATTRACT = 17;
export const SYS_FOLD = 18;
export const SYS_SPORE_DRIVE = 20;
export const SYS_SENSE_PHASE = 21;
export const STR_VOID = 0;
export const STR_WIRE = 1;
export const STR_NODE = 2;
export const STR_DIODE = 3;
export const STR_SOURCE = 4;
export const STR_SINK = 5;
export const STR_CAPACITOR = 6;
export const STR_INVERTER = 7;
export const STR_LATCH = 8;
const U64_BYTES = 8;
const I32_BYTES = 4;
const I16_BYTES = 2;
const F32_BYTES = 4;
export const TICK_COUNTER_OFFSET = 7999992;
export const TICK_COUNTER_OFF = 7999992;
export const SYNC_STATE_OFFSET = 7999996;
export const SYNC_STATE_OFF = 7999996;
export const IDS_OFFSET = 8000000;
export const IDS_OFF = 8000000;
export const XS_OFFSET = 12000000;
export const XS_OFF = 12000000;
export const YS_OFFSET = 13000000;
export const YS_OFF = 13000000;
export const ENERGY_OFFSET = 14000000;
export const ENERGY_OFF = 14000000;
export const RESONANCE_OFFSET = 16000000;
export const RESONANCE_OFF = 16000000;
export const PHASE_OFFSET = 18000000;
export const PHASE_OFF = 18000000;
export const LOGIC_OFFSET = 20000000;
export const LOGIC_OFF = 20000000;
export const BONDS_OFFSET = 24000000;
export const BONDS_OFF = 24000000;
export const STIFFNESS_OFFSET = 32000000;
export const STIFFNESS_OFF = 32000000;
export const INSTRUCTIONS_OFFSET = 40000000;
export const INSTRUCTIONS_OFF = 40000000;
export const GENOMES_OFFSET = 40000000;
export const CONTEXT_OFFSET = 72000000;
export const CONTEXT_OFF = 72000000;
export const EVOLUTION_OFFSET = 104000000;
export const EVOLUTION_OFF = 104000000;
export const INTENT_OFFSET = 104000000;
export const SPAWN_REQUESTS_OFFSET = 106000000;
export const SPAWN_REQUESTS_OFF = 106000000;
export const SPAWN_GRID_OFF = 106000000;
export const SPAWN_HEAD_OFF = 106000000;
export const SPAWN_DATA_OFF = 106000008;
export const MEIOSIS_RESERVED_OFFSET = 106024584;
export const MEIOSIS_RESERVED_OFF = 106024584;
export const METABOLISM_SCRATCH_OFF = 106024584;
export const MEIOSIS_OFFSET = 106024584;
export const BOND_REQUESTS_OFFSET = 112024584;
export const BOND_REQUESTS_OFF = 112024584;
export const SPATIAL_GRID_OFFSET = 118024584;
export const SPATIAL_GRID_OFF = 118024584;
export const ROLES_OFFSET = 119458184;
export const ROLES_OFF = 119458184;
export const STRUCTURE_GRID_OFFSET = 119958184;
export const STRUCTURE_GRID_OFF = 119958184;
export const SIGNAL_GRID_OFFSET = 120002984;
export const SIGNAL_GRID_OFF = 120002984;
export const MEMORY_GRID_OFFSET = 120047784;
export const MEMORY_GRID_OFF = 120047784;
export const ASCENSION_STATS_RESERVED_OFFSET = 120137384;
export const ASCENSION_STATS_RESERVED_OFF = 120137384;
export const ASCENSION_STATS_OFFSET = 120137384;
export const ASCENSION_STATS_OFF = 120137384;
export const BOND_DISTANCES_OFFSET = 125137384;
export const BOND_DISTANCES_OFF = 125137384;
export const BOND_DIST_OFF = 125137384;
export const SYNAPTIC_WEIGHTS_OFFSET = 127137384;
export const SYNAPTIC_WEIGHTS_OFF = 127137384;
export const DAMPING_OFFSET = 129137384;
export const DAMPING_OFF = 129137384;
export const CAUSALITY_OFFSET = 129637384;
export const CAUSALITY_OFF = 129637384;
export const HIVE_MEMORY_OFFSET = 130137384;
export const HIVE_MEMORY_OFF = 130137384;
export const HIVE_BALANCE_OFFSET = 130138408;
export const HIVE_BALANCE_OFF = 130138408;
export const QUORUM_OFFSET = 130138412;
export const QUORUM_OFF = 130138412;
export const COHERENCE_OFFSET = 130496812;
export const COHERENCE_OFF = 130496812;
export const NEURAL_COHERENCE_OFFSET = 130496816;
export const NEURAL_COHERENCE_OFF = 130496816;
export const PHYSICS_READ_XS_OFFSET = 130496820;
export const PHYSICS_READ_XS_OFF = 130496820;
export const PHYSICS_READ_YS_OFFSET = 131496820;
export const PHYSICS_READ_YS_OFF = 131496820;
export const PHYSICS_READ_ENERGY_OFFSET = 132496820;
export const PHYSICS_READ_ENERGY_OFF = 132496820;
export const PHYSICS_READ_RESONANCE_OFFSET = 134496820;
export const PHYSICS_READ_RESONANCE_OFF = 134496820;
export const ENERGY_DELTA_OFFSET = 136496820;
export const ENERGY_DELTA_OFF = 136496820;
export const RESONANCE_DELTA_OFFSET = 138496820;
export const RESONANCE_DELTA_OFF = 138496820;
export const STRUCTURE_BUILD_OWNER_OFFSET = 140496820;
export const STRUCTURE_BUILD_OWNER_OFF = 140496820;
export const STRUCTURE_BUILD_VALUE_OFFSET = 140541620;
export const STRUCTURE_BUILD_VALUE_OFF = 140541620;
export const STRUCTURE_CHARGE_INTENT_OFFSET = 140586420;
export const STRUCTURE_CHARGE_INTENT_OFF = 140586420;
export const ATTENTION_FIELD_OFFSET = 140631220;
export const ATTENTION_FIELD_OFF = 140631220;
export const HIVE_ENERGY_POOL_OFFSET = 140676020;
export const HIVE_ENERGY_POOL_OFF = 140676020;
export const GLYPH_HEADER_OFFSET = 140677044;
export const GLYPH_HEADER_OFF = 140677044;
export const GLYPH_PAYLOAD_OFFSET = 140721844;
export const GLYPH_PAYLOAD_OFF = 140721844;
export const GLYPH_SCRATCH_HEADER_OFFSET = 140811444;
export const GLYPH_SCRATCH_HEADER_OFF = 140811444;
export const GLYPH_SCRATCH_PAYLOAD_OFFSET = 140856244;
export const GLYPH_SCRATCH_PAYLOAD_OFF = 140856244;
export const HORMONES_OFFSET = 140945844;
export const HORMONES_OFF = 140945844;
export const HORMONE_OFFSET = 140945844;
export const HORMONE_OFF = 140945844;
export const SECRETION_STATS_OFFSET = 140945860;
export const SECRETION_STATS_OFF = 140945860;
export const LINEAGE_OFFSET = 140945912;
export const LINEAGE_OFF = 140945912;
export const MAILBOX_OFFSET = 144945912;
export const MAILBOX_OFF = 144945912;
export const LEDGER_HEAD_OFFSET = 148945912;
export const LEDGER_HEAD_OFF = 148945912;
export const LEDGER_DATA_OFFSET = 148945916;
export const LEDGER_DATA_OFF = 148945916;
export const EGRESS_HEAD_OFFSET = 149994492;
export const EGRESS_HEAD_OFF = 149994492;
export const EGRESS_DATA_OFFSET = 149994496;
export const EGRESS_DATA_OFF = 149994496;
export type MemoryLayoutRegion = { name: string; offset?: number; size: number; align: number; };
export const LATTICE_MEMORY_END = 151043072;
export const MIN_WASM_MEMORY_PAGES = 2600;
export const WASM_MEMORY_BYTES = 170393600;
export type MemoryLayoutValidationResult = { ok: boolean; errors: string[]; regions: MemoryLayoutRegion[]; latticeEnd: number; wasmBytes: number; };
export const MEMORY_LAYOUT_REGIONS: MemoryLayoutRegion[] = [
  {
    "name": "TICK_COUNTER",
    "size": 4,
    "align": 4,
    "offset": 7999992
  },
  {
    "name": "SYNC_STATE",
    "size": 4,
    "align": 4,
    "offset": 7999996
  },
  {
    "name": "IDS",
    "size": 4000000,
    "align": 8,
    "offset": 8000000
  },
  {
    "name": "XS",
    "size": 1000000,
    "align": 2,
    "offset": 12000000
  },
  {
    "name": "YS",
    "size": 1000000,
    "align": 2,
    "offset": 13000000
  },
  {
    "name": "ENERGY",
    "size": 2000000,
    "align": 4,
    "offset": 14000000
  },
  {
    "name": "RESONANCE",
    "size": 2000000,
    "align": 4,
    "offset": 16000000
  },
  {
    "name": "PHASE",
    "size": 2000000,
    "align": 4,
    "offset": 18000000
  },
  {
    "name": "LOGIC",
    "size": 4000000,
    "align": 1,
    "offset": 20000000
  },
  {
    "name": "BONDS",
    "size": 8000000,
    "align": 4,
    "offset": 24000000
  },
  {
    "name": "STIFFNESS",
    "size": 8000000,
    "align": 4,
    "offset": 32000000
  },
  {
    "name": "INSTRUCTIONS",
    "size": 32000000,
    "align": 1,
    "offset": 40000000
  },
  {
    "name": "CONTEXT",
    "size": 32000000,
    "align": 4,
    "offset": 72000000
  },
  {
    "name": "EVOLUTION",
    "size": 2000000,
    "align": 4,
    "offset": 104000000
  },
  {
    "name": "SPAWN_REQUESTS",
    "size": 24584,
    "align": 8,
    "offset": 106000000
  },
  {
    "name": "MEIOSIS_RESERVED",
    "size": 6000000,
    "align": 4,
    "offset": 106024584
  },
  {
    "name": "BOND_REQUESTS",
    "size": 6000000,
    "align": 4,
    "offset": 112024584
  },
  {
    "name": "SPATIAL_GRID",
    "size": 1433600,
    "align": 4,
    "offset": 118024584
  },
  {
    "name": "ROLES",
    "size": 500000,
    "align": 1,
    "offset": 119458184
  },
  {
    "name": "STRUCTURE_GRID",
    "size": 44800,
    "align": 4,
    "offset": 119958184
  },
  {
    "name": "SIGNAL_GRID",
    "size": 44800,
    "align": 4,
    "offset": 120002984
  },
  {
    "name": "MEMORY_GRID",
    "size": 89600,
    "align": 1,
    "offset": 120047784
  },
  {
    "name": "ASCENSION_STATS_RESERVED",
    "size": 5000000,
    "align": 4,
    "offset": 120137384
  },
  {
    "name": "BOND_DISTANCES",
    "size": 2000000,
    "align": 1,
    "offset": 125137384
  },
  {
    "name": "SYNAPTIC_WEIGHTS",
    "size": 2000000,
    "align": 1,
    "offset": 127137384
  },
  {
    "name": "DAMPING",
    "size": 500000,
    "align": 1,
    "offset": 129137384
  },
  {
    "name": "CAUSALITY",
    "size": 500000,
    "align": 1,
    "offset": 129637384
  },
  {
    "name": "HIVE_MEMORY",
    "size": 1024,
    "align": 1,
    "offset": 130137384
  },
  {
    "name": "HIVE_BALANCE",
    "size": 4,
    "align": 4,
    "offset": 130138408
  },
  {
    "name": "QUORUM",
    "size": 358400,
    "align": 4,
    "offset": 130138412
  },
  {
    "name": "COHERENCE",
    "size": 4,
    "align": 4,
    "offset": 130496812
  },
  {
    "name": "NEURAL_COHERENCE",
    "size": 4,
    "align": 4,
    "offset": 130496816
  },
  {
    "name": "PHYSICS_READ_XS",
    "size": 1000000,
    "align": 2,
    "offset": 130496820
  },
  {
    "name": "PHYSICS_READ_YS",
    "size": 1000000,
    "align": 2,
    "offset": 131496820
  },
  {
    "name": "PHYSICS_READ_ENERGY",
    "size": 2000000,
    "align": 4,
    "offset": 132496820
  },
  {
    "name": "PHYSICS_READ_RESONANCE",
    "size": 2000000,
    "align": 4,
    "offset": 134496820
  },
  {
    "name": "ENERGY_DELTA",
    "size": 2000000,
    "align": 4,
    "offset": 136496820
  },
  {
    "name": "RESONANCE_DELTA",
    "size": 2000000,
    "align": 4,
    "offset": 138496820
  },
  {
    "name": "STRUCTURE_BUILD_OWNER",
    "size": 44800,
    "align": 4,
    "offset": 140496820
  },
  {
    "name": "STRUCTURE_BUILD_VALUE",
    "size": 44800,
    "align": 4,
    "offset": 140541620
  },
  {
    "name": "STRUCTURE_CHARGE_INTENT",
    "size": 44800,
    "align": 4,
    "offset": 140586420
  },
  {
    "name": "ATTENTION_FIELD",
    "size": 44800,
    "align": 4,
    "offset": 140631220
  },
  {
    "name": "HIVE_ENERGY_POOL",
    "size": 1024,
    "align": 4,
    "offset": 140676020
  },
  {
    "name": "GLYPH_HEADER",
    "size": 44800,
    "align": 4,
    "offset": 140677044
  },
  {
    "name": "GLYPH_PAYLOAD",
    "size": 89600,
    "align": 1,
    "offset": 140721844
  },
  {
    "name": "GLYPH_SCRATCH_HEADER",
    "size": 44800,
    "align": 4,
    "offset": 140811444
  },
  {
    "name": "GLYPH_SCRATCH_PAYLOAD",
    "size": 89600,
    "align": 1,
    "offset": 140856244
  },
  {
    "name": "HORMONES",
    "size": 16,
    "align": 2,
    "offset": 140945844
  },
  {
    "name": "SECRETION_STATS",
    "size": 48,
    "align": 4,
    "offset": 140945860
  },
  {
    "name": "LINEAGE",
    "size": 4000000,
    "align": 8,
    "offset": 140945912
  },
  {
    "name": "MAILBOX",
    "size": 4000000,
    "align": 4,
    "offset": 144945912
  },
  {
    "name": "LEDGER_HEAD",
    "size": 4,
    "align": 4,
    "offset": 148945912
  },
  {
    "name": "LEDGER_DATA",
    "size": 1048576,
    "align": 4,
    "offset": 148945916
  },
  {
    "name": "EGRESS_HEAD",
    "size": 4,
    "align": 4,
    "offset": 149994492
  },
  {
    "name": "EGRESS_DATA",
    "size": 1048576,
    "align": 4,
    "offset": 149994496
  }
];
export const validateMemoryLayout = (wasmBytes = WASM_MEMORY_BYTES)=>{
  const errors = [];
  const sorted = [
    ...MEMORY_LAYOUT_REGIONS
  ].sort((a, b)=>(a.offset || 0) - (b.offset || 0));
  for (const item of sorted){
    if (item.offset === undefined || !Number.isFinite(item.offset) || !Number.isFinite(item.size)) {
      errors.push("[" + item.name + "] offset/size must be finite numbers");
      continue;
    }
    if (item.size <= 0) errors.push("[" + item.name + "] size must be > 0, got " + item.size);
    if (item.align <= 0) {
      errors.push("[" + item.name + "] align must be > 0, got " + item.align);
    } else if (item.offset % item.align !== 0) {
      errors.push("[" + item.name + "] misaligned offset=" + item.offset + " align=" + item.align);
    }
    const end = item.offset + item.size;
    if (end > wasmBytes) errors.push("[" + item.name + "] out of wasm bounds: end=" + end + " > wasmBytes=" + wasmBytes);
  }
  for(let i = 1; i < sorted.length; i++){
    const prev = sorted[i - 1];
    const next = sorted[i];
    const prevEnd = (prev.offset || 0) + prev.size;
    if (prevEnd > (next.offset || 0)) errors.push("[" + prev.name + "] overlaps [" + next.name + "] (" + prevEnd + " > " + next.offset + ")");
  }
  const maxRegionEnd = sorted.reduce((max, item)=>Math.max(max, (item.offset || 0) + item.size), 0);
  if (maxRegionEnd > LATTICE_MEMORY_END) errors.push("[LATTICE_MEMORY_END] too small: " + LATTICE_MEMORY_END + " < required=" + maxRegionEnd);
  return {
    ok: errors.length === 0,
    errors,
    regions: sorted,
    latticeEnd: LATTICE_MEMORY_END,
    wasmBytes
  };
};
export const MAX_ASCENSIONS_PER_TICK = 64;