// AUTOGENERATED FACADE
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]

#[path = "00/mod.rs"]
pub mod L00;
#[path = "01/mod.rs"]
pub mod L01;
#[path = "02/mod.rs"]
pub mod L02;
#[path = "03/mod.rs"]
pub mod L03;
#[path = "04/mod.rs"]
pub mod L04;
#[path = "05/mod.rs"]
pub mod L05;
#[path = "06/mod.rs"]
pub mod L06;
#[path = "07/mod.rs"]
pub mod L07;
#[path = "08/mod.rs"]
pub mod L08;
#[path = "09/mod.rs"]
pub mod L09;
#[path = "10/mod.rs"]
pub mod L10;
#[path = "11/mod.rs"]
pub mod L11;
#[path = "12/mod.rs"]
pub mod L12;
#[path = "13/mod.rs"]
pub mod L13;
#[path = "14/mod.rs"]
pub mod L14;
#[path = "15/mod.rs"]
pub mod L15;
